'use strict';
/* Grammar lessons for travel French. Each lesson: short theory (EN/RU), a table, examples, typical mistakes, exercises.
   Exercise types: mc (pick the option for the gap), fill (type the gap), build (tap the words in order).
   In mc/fill the gap is ___ ; `a` for mc is the index of the right option in `o`; `a` for fill is a list of accepted answers. */
const X = (en, ru) => ({ en, ru });
const LESSONS = [
  {
    id: 'g01', e: '🏷️', en: 'Articles and gender', ru: 'Артикли и род',
    sum: [
      X('Every French noun is masculine or feminine. Learn the noun together with its article: le café, la gare. Before a vowel or a silent h, le and la both become l’: l’eau, l’hôtel.',
        'Каждое французское существительное мужского или женского рода. Учи слово сразу с артиклем: le café, la gare. Перед гласной и немым h le и la превращаются в l’: l’eau, l’hôtel.'),
      X('The definite article (le, la, les) points to a specific thing: la carte (the menu). The indefinite article (un, une, des) means a or some: une table (a table).',
        'Определённый артикль (le, la, les) указывает на конкретный предмет: la carte (то самое меню). Неопределённый (un, une, des) значит «какой-то»: une table (какой-нибудь столик).'),
      X('The plural usually adds a silent -s: un croissant, deux croissants. You hear the plural in the article: le → les, un → des.',
        'Множественное число обычно получает немое -s: un croissant, deux croissants. Множественное слышно по артиклю: le → les, un → des.'),
    ],
    table: { head: ['', 'm', 'f', 'pl'], rows: [['the', 'le (l’)', 'la (l’)', 'les'], ['a / some', 'un', 'une', 'des']] },
    ex: [['un café', 'a coffee', 'кофе'], ['une table', 'a table', 'столик'], ['l’eau', 'the water', 'вода'], ['les toilettes', 'the toilets', 'туалет'], ['des croissants', 'some croissants', 'круассаны']],
    mist: X('Gender often differs from Russian: le soleil is masculine, la lune feminine. Do not drop the article: say Je voudrais un café, not “Je voudrais café”. The final -s is silent: les croissants sounds like le croissant, only the article changes.',
      'Род часто не совпадает с русским: le soleil (м.), la lune (ж.). Артикль нельзя опускать: Je voudrais un café, а не «Je voudrais café». Конечное -s не читается: les croissants звучит как le croissant, меняется только артикль.'),
    quiz: [
      { t: 'mc', q: 'Je voudrais ___ café, s’il vous plaît.', o: ['un', 'une', 'des'], a: 0, w: X('café is masculine: un café.', 'café мужского рода: un café.') },
      { t: 'mc', q: '___ table pour deux, s’il vous plaît.', o: ['Un', 'Une', 'Les'], a: 1, w: X('table is feminine: une table.', 'table женского рода: une table.') },
      { t: 'mc', q: 'Où est ___ gare ?', o: ['le', 'la', 'les'], a: 1, w: X('gare is feminine: la gare.', 'gare женского рода: la gare.') },
      { t: 'mc', q: 'Où sont ___ toilettes ?', o: ['le', 'la', 'les'], a: 2, w: X('toilettes is plural in French: les toilettes.', 'toilettes во французском во множественном числе: les toilettes.') },
      { t: 'mc', q: 'C’est ___ addition, s’il vous plaît.', o: ['l’', 'le', 'la'], a: 0, w: X('Before a vowel, la becomes l’: l’addition.', 'Перед гласной la превращается в l’: l’addition.') },
      { t: 'fill', q: 'Vous avez ___ huîtres ?', a: ['des'], w: X('Plural, “some”: des huîtres.', 'Множественное, «какие-нибудь»: des huîtres.') },
      { t: 'build', en: 'A table for two', ru: 'Столик на двоих', a: 'Une table pour deux' },
    ],
  },
  {
    id: 'g02', e: '🧩', en: 'Être and avoir', ru: 'Être и avoir',
    sum: [
      X('Être (to be) and avoir (to have) are the two most useful verbs. French always needs the verb: Je suis fatiguée (I am tired), where Russian drops “am”.',
        'Être (быть) и avoir (иметь) нужнее всего. Во французском глагол обязателен: Je suis fatiguée («я уставшая»), хотя по-русски связки в настоящем времени нет.'),
      X('Avoir also appears in set phrases: j’ai besoin de… (I need…), j’ai faim (I am hungry), j’ai 30 ans (I am 30).',
        'Avoir встречается и в устойчивых выражениях: j’ai besoin de… (мне нужно…), j’ai faim (я голодна), j’ai 30 ans (мне 30 лет).'),
    ],
    table: { head: ['', 'être', 'avoir'], rows: [['je', 'suis', 'ai (j’ai)'], ['tu', 'es', 'as'], ['il / elle', 'est', 'a'], ['nous', 'sommes', 'avons'], ['vous', 'êtes', 'avez'], ['ils / elles', 'sont', 'ont']] },
    ex: [['Je suis Anna.', 'I am Anna.', 'Я Анна.'], ['J’ai une réservation.', 'I have a reservation.', 'У меня бронирование.'], ['Vous avez une table ?', 'Do you have a table?', 'У вас есть столик?'], ['Nous sommes deux.', 'There are two of us.', 'Нас двое.'], ['J’ai besoin d’aide.', 'I need help.', 'Мне нужна помощь.']],
    mist: X('Age and hunger use avoir, not être: J’ai trente ans, not “Je suis trente ans”. Before a vowel je becomes j’: j’ai, not “je ai”.',
      'Возраст и голод выражаются через avoir: J’ai trente ans, а не «Je suis trente ans». Перед гласной je превращается в j’: j’ai, а не «je ai».'),
    quiz: [
      { t: 'mc', q: 'Je ___ Anna.', o: ['suis', 'ai', 'es'], a: 0, w: X('je suis (être).', 'je suis (être).') },
      { t: 'mc', q: 'Vous ___ une réservation ?', o: ['êtes', 'avez', 'ont'], a: 1, w: X('A reservation is something you have: vous avez.', 'Бронирование «имеют»: vous avez.') },
      { t: 'fill', q: 'Nous ___ en retard.', a: ['sommes'], w: X('nous sommes (être).', 'nous sommes (être).') },
      { t: 'mc', q: 'Il ___ fatigué.', o: ['a', 'est', 'sont'], a: 1, w: X('A state uses être: il est fatigué.', 'Состояние выражается через être: il est fatigué.') },
      { t: 'fill', q: 'J’___ besoin d’aide.', a: ['ai'], w: X('avoir besoin de: j’ai besoin d’aide.', 'avoir besoin de: j’ai besoin d’aide.') },
      { t: 'mc', q: 'Ils ___ deux enfants.', o: ['sont', 'ont', 'est'], a: 1, w: X('They have: ils ont.', 'У них есть: ils ont.') },
      { t: 'build', en: 'I have a reservation under the name Anna', ru: 'У меня бронирование на имя Анна', a: 'J’ai une réservation au nom d’Anna.' },
    ],
  },
  {
    id: 'g03', e: '🙏', en: 'Polite requests: vouloir and pouvoir', ru: 'Вежливые просьбы: vouloir и pouvoir',
    sum: [
      X('To order or ask, use Je voudrais… (I would like…). It is softer than Je veux (I want). To ask for help or permission, use Vous pouvez… ? or Je peux… ?',
        'Чтобы заказать или попросить, говори Je voudrais… («я хотела бы…»). Это мягче, чем Je veux («я хочу»). Просьбу или разрешение выражают так: Vous pouvez… ? или Je peux… ?'),
      X('After voudrais, peux, pouvez, the next verb stays in the infinitive: Je voudrais réserver. Vous pouvez répéter ?',
        'После voudrais, peux, pouvez следующий глагол стоит в инфинитиве: Je voudrais réserver. Vous pouvez répéter ?'),
    ],
    table: { head: ['', 'vouloir', 'pouvoir'], rows: [['je', 'veux / voudrais', 'peux'], ['tu', 'veux', 'peux'], ['il / elle', 'veut', 'peut'], ['nous', 'voulons', 'pouvons'], ['vous', 'voulez', 'pouvez'], ['ils / elles', 'veulent', 'peuvent']] },
    ex: [['Je voudrais un café.', 'I would like a coffee.', 'Я хотела бы кофе.'], ['Je voudrais réserver une table.', 'I would like to book a table.', 'Я хотела бы забронировать столик.'], ['Vous pouvez répéter ?', 'Can you repeat?', 'Вы можете повторить?'], ['Je peux payer par carte ?', 'Can I pay by card?', 'Могу я оплатить картой?']],
    mist: X('Je veux sounds blunt in a café. Keep Je voudrais for orders and requests. The verb after pouvoir is never conjugated: Je peux payer, not “Je peux paie”.',
      'Je veux в кафе звучит резко. Для заказов и просьб держи Je voudrais. Глагол после pouvoir не спрягается: Je peux payer, а не «Je peux paie».'),
    quiz: [
      { t: 'mc', q: '___ un café, s’il vous plaît.', o: ['Je veux', 'Je voudrais', 'Je peux'], a: 1, w: X('Je voudrais is the polite way to order.', 'Je voudrais — вежливый способ заказать.') },
      { t: 'fill', q: 'Vous ___ répéter, s’il vous plaît ?', a: ['pouvez'], w: X('vous pouvez + infinitive.', 'vous pouvez + инфинитив.') },
      { t: 'mc', q: 'Je ___ payer par carte ?', o: ['peux', 'peut', 'pouvez'], a: 0, w: X('je peux.', 'je peux.') },
      { t: 'mc', q: 'Ils ___ partir demain.', o: ['veut', 'veulent', 'voulons'], a: 1, w: X('ils veulent.', 'ils veulent.') },
      { t: 'mc', q: 'Je voudrais ___ une chambre.', o: ['réserver', 'réservé', 'réserve'], a: 0, w: X('After voudrais the verb is an infinitive.', 'После voudrais глагол стоит в инфинитиве.') },
      { t: 'fill', q: 'Nous ___ une table pour deux.', a: ['voulons'], w: X('nous voulons.', 'nous voulons.') },
      { t: 'build', en: 'Can I pay by card?', ru: 'Я могу оплатить картой?', a: 'Je peux payer par carte ?' },
    ],
  },
  {
    id: 'g04', e: '🗣️', en: 'Present tense: -er verbs, aller, faire', ru: 'Настоящее время: глаголы на -er, aller, faire',
    sum: [
      X('Most French verbs end in -er and follow one pattern: remove -er and add -e, -es, -e, -ons, -ez, -ent. Parler (to speak): je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent.',
        'Большинство французских глаголов оканчиваются на -er и спрягаются одинаково: убери -er и добавь -e, -es, -e, -ons, -ez, -ent. Parler (говорить): je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent.'),
      X('Two irregular verbs you need every day: aller (to go) and faire (to do, to make). They are worth learning by heart.',
        'Два неправильных глагола нужны каждый день: aller (идти, ехать) и faire (делать). Их стоит выучить наизусть.'),
    ],
    table: { head: ['', 'parler', 'aller', 'faire'], rows: [['je', 'parle', 'vais', 'fais'], ['tu', 'parles', 'vas', 'fais'], ['il / elle', 'parle', 'va', 'fait'], ['nous', 'parlons', 'allons', 'faisons'], ['vous', 'parlez', 'allez', 'faites'], ['ils / elles', 'parlent', 'vont', 'font']] },
    ex: [['Je parle un peu français.', 'I speak a little French.', 'Я немного говорю по-французски.'], ['Vous parlez anglais ?', 'Do you speak English?', 'Вы говорите по-английски?'], ['Nous allons à la gare.', 'We are going to the station.', 'Мы идём на вокзал.'], ['Ça fait douze euros.', 'That comes to twelve euros.', 'С вас двенадцать евро.']],
    mist: X('Parle, parles and parlent sound the same; only nous and vous endings are heard (-ons, -ez). Ça marche, ça fait: ça is the everyday “it”.',
      'Parle, parles и parlent звучат одинаково; слышны только окончания nous и vous (-ons, -ez). Ça marche, ça fait: ça — повседневное «это».'),
    quiz: [
      { t: 'fill', q: 'Je ___ un peu français.', a: ['parle'], w: X('je parle.', 'je parle.') },
      { t: 'mc', q: 'Vous ___ anglais ?', o: ['parlez', 'parlons', 'parle'], a: 0, w: X('vous parlez.', 'vous parlez.') },
      { t: 'mc', q: 'Nous ___ à la gare.', o: ['allons', 'allez', 'vont'], a: 0, w: X('nous allons (aller).', 'nous allons (aller).') },
      { t: 'fill', q: 'Ça ___ douze euros.', a: ['fait'], w: X('ça fait (faire).', 'ça fait (faire).') },
      { t: 'mc', q: 'Ils ___ du sport.', o: ['fait', 'font', 'faites'], a: 1, w: X('ils font.', 'ils font.') },
      { t: 'mc', q: 'Je ___ à l’hôtel.', o: ['vais', 'va', 'allez'], a: 0, w: X('je vais.', 'je vais.') },
      { t: 'build', en: 'I speak a little French', ru: 'Я немного говорю по-французски', a: 'Je parle un peu français.' },
    ],
  },
  {
    id: 'g05', e: '🚫', en: 'Negation: ne … pas', ru: 'Отрицание: ne … pas',
    sum: [
      X('Put ne before the verb and pas after it: Je ne comprends pas. Before a vowel, ne becomes n’: Je n’ai pas de monnaie.',
        'Поставь ne перед глаголом и pas после него: Je ne comprends pas. Перед гласной ne превращается в n’: Je n’ai pas de monnaie.'),
      X('Other negations work the same way: ne … plus (no more), ne … jamais (never), ne … rien (nothing). In fast speech ne often disappears: Je comprends pas.',
        'Другие отрицания строятся так же: ne … plus (больше не), ne … jamais (никогда), ne … rien (ничего). В быстрой речи ne часто пропадает: Je comprends pas.'),
      X('After a negation, un / une / des / du become de (or d’): J’ai une clé → Je n’ai pas de clé.',
        'После отрицания un / une / des / du превращаются в de (или d’): J’ai une clé → Je n’ai pas de clé.'),
    ],
    table: { head: ['', 'French', 'EN'], rows: [['ne … pas', 'Je ne parle pas.', 'not'], ['ne … plus', 'Il n’y a plus de pain.', 'no more'], ['ne … jamais', 'Je ne bois jamais de café.', 'never'], ['ne … rien', 'Je ne comprends rien.', 'nothing']] },
    ex: [['Je ne comprends pas.', 'I don’t understand.', 'Я не понимаю.'], ['Ça ne marche pas.', 'It doesn’t work.', 'Это не работает.'], ['Je n’ai pas de monnaie.', 'I have no change.', 'У меня нет мелочи.'], ['Il n’y a pas de problème.', 'There is no problem.', 'Проблемы нет.']],
    mist: X('Do not use a double negative with a negative word the Russian way: Je ne vois personne (I see nobody) already needs ne. Remember de after pas: pas de monnaie, not “pas une monnaie”.',
      'Во французском ne обязательно сочетается со вторым словом: Je ne vois personne («я никого не вижу»). Запомни de после pas: pas de monnaie, а не «pas une monnaie».'),
    quiz: [
      { t: 'mc', q: 'Je ___ comprends pas.', o: ['ne', 'n’', 'non'], a: 0, w: X('ne before the verb.', 'ne ставится перед глаголом.') },
      { t: 'mc', q: 'Je n’ai pas ___ monnaie.', o: ['de', 'une', 'la'], a: 0, w: X('After pas, une becomes de.', 'После pas une превращается в de.') },
      { t: 'fill', q: 'Ça ne ___ pas.', a: ['marche'], w: X('ça ne marche pas.', 'ça ne marche pas.') },
      { t: 'mc', q: 'Il n’y a ___ de problème.', o: ['pas', 'plus', 'rien'], a: 0, w: X('Il n’y a pas de problème = there is no problem.', 'Il n’y a pas de problème = проблемы нет.') },
      { t: 'mc', q: 'Je ne parle ___ français.', o: ['pas', 'non', 'ne'], a: 0, w: X('ne … pas around the verb.', 'ne … pas вокруг глагола.') },
      { t: 'fill', q: 'Je ___ pas de monnaie.', a: ['n’ai'], w: X('ne + ai becomes n’ai before a vowel: je n’ai pas de monnaie.', 'ne + ai превращается в n’ai: je n’ai pas de monnaie.') },
      { t: 'build', en: 'I don’t understand', ru: 'Я не понимаю', a: 'Je ne comprends pas.' },
    ],
  },
  {
    id: 'g06', e: '❓', en: 'Asking questions', ru: 'Вопросы',
    sum: [
      X('There are three ways to ask a yes/no question. Rising intonation is the most common in speech: Vous parlez anglais ? Adding est-ce que is a safe, neutral form: Est-ce que vous parlez anglais ? Inversion is formal: Parlez-vous anglais ?',
        'Есть три способа задать вопрос «да/нет». В речи чаще всего просто повышают интонацию: Vous parlez anglais ? Нейтральная форма — est-ce que: Est-ce que vous parlez anglais ? Инверсия — формальный вариант: Parlez-vous anglais ?'),
      X('Question words: où (where), quand (when), comment (how), combien (how much), pourquoi (why), quel / quelle (which, what), qui (who), qu’est-ce que (what).',
        'Вопросительные слова: où (где, куда), quand (когда), comment (как), combien (сколько), pourquoi (почему), quel / quelle (какой), qui (кто), qu’est-ce que (что).'),
    ],
    table: { head: ['', 'French', 'EN'], rows: [['où', 'Où est la gare ?', 'where'], ['combien', 'C’est combien ?', 'how much'], ['quel / quelle', 'Quel est le mot de passe ?', 'which / what'], ['à quelle heure', 'À quelle heure ?', 'at what time'], ['qu’est-ce que', 'Qu’est-ce que vous recommandez ?', 'what']] },
    ex: [['Où est la gare ?', 'Where is the train station?', 'Где вокзал?'], ['C’est combien ?', 'How much is it?', 'Сколько это стоит?'], ['À quelle heure est le petit-déjeuner ?', 'What time is breakfast?', 'Во сколько завтрак?'], ['Quel est le mot de passe ?', 'What is the password?', 'Какой пароль?']],
    mist: X('Quel agrees with the noun: quel (m), quelle (f), quels, quelles. Où also means “to where”: Où allez-vous ? Do not translate “что” word for word: Qu’est-ce que… for things, Qui for people.',
      'Quel согласуется с существительным: quel (м.), quelle (ж.), quels, quelles. Où значит и «где», и «куда»: Où allez-vous ? «Что» переводится по-разному: Qu’est-ce que… про предметы, Qui про людей.'),
    quiz: [
      { t: 'mc', q: '___ est la gare ?', o: ['Où', 'Quand', 'Qui'], a: 0, w: X('où = where.', 'où = где.') },
      { t: 'mc', q: 'C’est ___ ?', o: ['combien', 'comment', 'pourquoi'], a: 0, w: X('C’est combien ? = How much is it?', 'C’est combien ? = Сколько это стоит?') },
      { t: 'mc', q: 'À ___ heure est le petit-déjeuner ?', o: ['quelle', 'quel', 'quels'], a: 0, w: X('heure is feminine: quelle heure.', 'heure женского рода: quelle heure.') },
      { t: 'mc', q: '___ est le mot de passe ?', o: ['Quel', 'Quelle', 'Qui'], a: 0, w: X('mot is masculine: quel.', 'mot мужского рода: quel.') },
      { t: 'mc', q: 'Est-ce que ___ parlez anglais ?', o: ['vous', 'vos', 'votre'], a: 0, w: X('Est-ce que + subject + verb.', 'Est-ce que + подлежащее + глагол.') },
      { t: 'fill', q: 'Qu’est-ce que vous ___ ?', a: ['recommandez'], w: X('vous recommandez.', 'vous recommandez.') },
      { t: 'build', en: 'Do you speak English?', ru: 'Вы говорите по-английски?', a: 'Vous parlez anglais ?' },
    ],
  },
  {
    id: 'g07', e: '👆', en: 'Possessives and “this / that”', ru: 'Притяжательные и указательные',
    sum: [
      X('Possessives agree with the thing owned, not with the owner: ma réservation (my reservation), mon passeport (my passport). For feminine nouns that start with a vowel, use mon: mon adresse.',
        'Притяжательные согласуются с предметом, а не с владельцем: ma réservation, mon passeport. Перед женским словом на гласную ставят mon: mon adresse.'),
      X('Demonstratives: ce (m), cet (m before a vowel), cette (f), ces (plural). Je cherche cette adresse.',
        'Указательные: ce (м.), cet (м. перед гласной), cette (ж.), ces (мн.). Je cherche cette adresse.'),
    ],
    table: { head: ['', 'm', 'f', 'pl'], rows: [['my', 'mon', 'ma', 'mes'], ['your (tu)', 'ton', 'ta', 'tes'], ['his / her', 'son', 'sa', 'ses'], ['our', 'notre', 'notre', 'nos'], ['your (vous)', 'votre', 'votre', 'vos'], ['their', 'leur', 'leur', 'leurs'], ['this', 'ce / cet', 'cette', 'ces']] },
    ex: [['Votre passeport, s’il vous plaît.', 'Your passport, please.', 'Ваш паспорт, пожалуйста.'], ['J’ai un problème avec ma réservation.', 'I have a problem with my reservation.', 'У меня проблема с бронированием.'], ['Je cherche cette adresse.', 'I am looking for this address.', 'Я ищу этот адрес.'], ['Quel est votre nom ?', 'What is your name?', 'Как вас зовут?']],
    mist: X('son / sa / ses mean both “his” and “her”; the gender is that of the thing: sa clé is his key or her key. Vous = votre, tu = ton: stay consistent.',
      'son / sa / ses значат и «его», и «её»: род определяет предмет, поэтому sa clé — его или её ключ. Vous → votre, tu → ton: держись одной формы.'),
    quiz: [
      { t: 'mc', q: '___ réservation est au nom d’Anna.', o: ['Ma', 'Mon', 'Mes'], a: 0, w: X('réservation is feminine: ma.', 'réservation женского рода: ma.') },
      { t: 'mc', q: '___ passeport, s’il vous plaît.', o: ['Votre', 'Vos', 'Ma'], a: 0, w: X('One masculine passport: votre passeport.', 'Один паспорт: votre passeport.') },
      { t: 'mc', q: 'Je cherche ___ adresse.', o: ['cette', 'ce', 'ces'], a: 0, w: X('adresse is feminine: cette adresse.', 'adresse женского рода: cette adresse.') },
      { t: 'mc', q: 'Voici ___ adresse.', o: ['mon', 'ma', 'mes'], a: 0, w: X('Feminine noun before a vowel takes mon: mon adresse.', 'Женское слово на гласную: mon adresse.') },
      { t: 'mc', q: 'Je voudrais ___ croissant.', o: ['ce', 'cette', 'ces'], a: 0, w: X('croissant is masculine: ce croissant.', 'croissant мужского рода: ce croissant.') },
      { t: 'fill', q: 'Voici ___ clé. (your, formal)', a: ['votre'], w: X('clé is feminine, but votre does not change: votre clé.', 'votre не меняется по роду: votre clé.') },
      { t: 'build', en: 'What is your name?', ru: 'Как вас зовут?', a: 'Quel est votre nom ?' },
    ],
  },
  {
    id: 'g08', e: '📍', en: 'à, de and il y a', ru: 'à, de и il y a',
    sum: [
      X('à means to / at / in; de means of / from. With le and les they merge: à + le = au, à + les = aux; de + le = du, de + les = des. With la and l’ nothing changes: à la gare, de l’hôtel.',
        'à значит «в, к, на»; de — «из, от, of». С le и les они сливаются: à + le = au, à + les = aux; de + le = du, de + les = des. С la и l’ ничего не меняется: à la gare, de l’hôtel.'),
      X('Il y a means there is / there are: Il y a un problème. In the negative: Il n’y a pas de problème. To ask: Il y a des toilettes ici ?',
        'Il y a значит «есть, имеется»: Il y a un problème. Отрицание: Il n’y a pas de problème. Вопрос: Il y a des toilettes ici ?'),
    ],
    table: { head: ['', 'le', 'la / l’', 'les'], rows: [['à', 'au', 'à la / à l’', 'aux'], ['de', 'du', 'de la / de l’', 'des']] },
    ex: [['Je vais au marché.', 'I am going to the market.', 'Я иду на рынок.'], ['Je suis à la gare.', 'I am at the station.', 'Я на вокзале.'], ['Le mot de passe du Wi-Fi', 'the Wi-Fi password', 'пароль от Wi-Fi'], ['À côté de l’hôtel', 'next to the hotel', 'рядом с отелем']],
    mist: X('Do not write “à le” or “de le”: always au and du. Il y a does not change for singular and plural: il y a un hôtel, il y a deux hôtels.',
      'Нельзя писать «à le» или «de le»: всегда au и du. Il y a не меняется ни в единственном, ни во множественном: il y a un hôtel, il y a deux hôtels.'),
    quiz: [
      { t: 'mc', q: 'Je vais ___ marché.', o: ['au', 'à la', 'aux'], a: 0, w: X('à + le = au.', 'à + le = au.') },
      { t: 'mc', q: 'Je suis ___ gare.', o: ['au', 'à la', 'à l’'], a: 1, w: X('gare is feminine: à la gare.', 'gare женского рода: à la gare.') },
      { t: 'mc', q: 'Le mot de passe ___ Wi-Fi.', o: ['du', 'de la', 'des'], a: 0, w: X('de + le = du.', 'de + le = du.') },
      { t: 'mc', q: 'Où est la sortie ___ hôtel ?', o: ['de l’', 'du', 'de la'], a: 0, w: X('Before a vowel: de l’hôtel.', 'Перед гласной: de l’hôtel.') },
      { t: 'mc', q: 'Il y a ___ toilettes ici ?', o: ['des', 'les', 'de'], a: 0, w: X('Il y a des toilettes ? = Are there toilets?', 'Il y a des toilettes ? = Здесь есть туалеты?') },
      { t: 'fill', q: 'Il n’___ a pas de problème.', a: ['y'], w: X('il n’y a pas de problème.', 'il n’y a pas de problème.') },
      { t: 'build', en: 'Where is the train station?', ru: 'Где вокзал?', a: 'Où est la gare ?' },
    ],
  },
  {
    id: 'g09', e: '🎨', en: 'Adjectives', ru: 'Прилагательные',
    sum: [
      X('Adjectives agree with the noun. Feminine usually adds -e (petit → petite), plural adds -s (petits, petites). If the word already ends in -e, the feminine stays the same: rouge, simple, libre.',
        'Прилагательные согласуются с существительным. Женский род обычно получает -e (petit → petite), множественное число -s (petits, petites). Если слово уже оканчивается на -e, женская форма не меняется: rouge, simple, libre.'),
      X('Most adjectives come after the noun: une chambre libre, une voiture rouge. A few common ones come before: petit, grand, bon, beau, nouveau, vieux, jeune.',
        'Большинство прилагательных стоят после существительного: une chambre libre, une voiture rouge. Несколько частых стоят перед ним: petit, grand, bon, beau, nouveau, vieux, jeune.'),
    ],
    table: { head: ['m', 'f', 'EN'], rows: [['petit', 'petite', 'small'], ['grand', 'grande', 'big'], ['bon', 'bonne', 'good'], ['beau', 'belle', 'beautiful'], ['complet', 'complète', 'full'], ['cher', 'chère', 'expensive']] },
    ex: [['une petite chambre', 'a small room', 'маленький номер'], ['un grand hôtel', 'a big hotel', 'большой отель'], ['une chambre libre', 'a free room', 'свободный номер'], ['C’est complet.', 'It is full.', 'Мест нет.']],
    mist: X('The adjective must agree even after être: La chambre est propre, les chambres sont propres. Colors and nationalities come after the noun and do not take a capital letter.',
      'Прилагательное согласуется и после être: La chambre est propre, les chambres sont propres. Цвета и национальности стоят после существительного и пишутся с маленькой буквы.'),
    quiz: [
      { t: 'mc', q: 'une chambre ___', o: ['propre', 'petit', 'propres'], a: 0, w: X('One feminine noun; propre already ends in -e and stays the same.', 'Одно существительное ж. р.; propre уже оканчивается на -e и не меняется.') },
      { t: 'mc', q: 'un ___ hôtel', o: ['petit', 'petite', 'petites'], a: 0, w: X('hôtel is masculine: petit.', 'hôtel мужского рода: petit.') },
      { t: 'mc', q: 'une ___ table', o: ['petit', 'petite', 'petits'], a: 1, w: X('table is feminine: petite.', 'table женского рода: petite.') },
      { t: 'mc', q: 'La porte est ___.', o: ['fermée', 'fermé', 'fermés'], a: 0, w: X('porte is feminine: fermée.', 'porte женского рода: fermée.') },
      { t: 'mc', q: 'Les chambres sont ___.', o: ['grande', 'grandes', 'grands'], a: 1, w: X('Feminine plural: grandes.', 'Женский род, мн. число: grandes.') },
      { t: 'fill', q: 'Une chambre ___ (free)', a: ['libre'], w: X('libre does not change in the feminine.', 'libre в женском роде не меняется.') },
      { t: 'build', en: 'A room for two', ru: 'Номер на двоих', a: 'Une chambre pour deux' },
    ],
  },
  {
    id: 'g10', e: '⏭️', en: 'Near future and past', ru: 'Ближайшее будущее и прошедшее',
    sum: [
      X('Near future: aller + infinitive. Je vais réserver une table. Nous allons partir demain. It is the easiest way to talk about plans.',
        'Ближайшее будущее: aller + инфинитив. Je vais réserver une table. Nous allons partir demain. Это самый простой способ говорить о планах.'),
      X('Past (passé composé): avoir or être + past participle. For -er verbs the participle ends in -é: manger → j’ai mangé, réserver → j’ai réservé. Verbs of movement use être: je suis arrivée, il est parti.',
        'Прошедшее (passé composé): avoir или être + причастие. У глаголов на -er причастие оканчивается на -é: manger → j’ai mangé, réserver → j’ai réservé. Глаголы движения берут être: je suis arrivée, il est parti.'),
    ],
    table: { head: ['', 'French', 'EN'], rows: [['aller + inf.', 'Je vais manger.', 'I am going to eat.'], ['avoir + -é', 'J’ai réservé.', 'I booked.'], ['être + -é', 'Je suis arrivée.', 'I arrived.']] },
    ex: [['Je vais réserver une table.', 'I am going to book a table.', 'Я собираюсь забронировать столик.'], ['Nous allons partir demain.', 'We are going to leave tomorrow.', 'Мы уедем завтра.'], ['J’ai réservé une chambre.', 'I booked a room.', 'Я забронировала номер.'], ['Je suis arrivée hier.', 'I arrived yesterday.', 'Я приехала вчера.']],
    mist: X('With être the participle agrees: Je suis arrivée (a woman), Je suis arrivé (a man). With avoir it does not: J’ai mangé.',
      'С être причастие согласуется: Je suis arrivée (женщина), Je suis arrivé (мужчина). С avoir — нет: J’ai mangé.'),
    quiz: [
      { t: 'mc', q: 'Je ___ réserver une table.', o: ['vais', 'va', 'ai'], a: 0, w: X('je vais + infinitive.', 'je vais + инфинитив.') },
      { t: 'fill', q: 'Nous allons ___ demain. (partir)', a: ['partir'], w: X('aller + infinitive: partir.', 'aller + инфинитив: partir.') },
      { t: 'mc', q: 'J’ai ___ une chambre.', o: ['réservé', 'réserver', 'réserve'], a: 0, w: X('avoir + participle in -é.', 'avoir + причастие на -é.') },
      { t: 'mc', q: 'Je ___ arrivée hier.', o: ['suis', 'ai', 'vais'], a: 0, w: X('arriver uses être.', 'arriver берёт être.') },
      { t: 'mc', q: 'Il a ___ un café.', o: ['commandé', 'commander', 'commande'], a: 0, w: X('commander → commandé.', 'commander → commandé.') },
      { t: 'mc', q: 'Nous ___ manger au restaurant.', o: ['allons', 'avons', 'sommes'], a: 0, w: X('nous allons + infinitive.', 'nous allons + инфинитив.') },
      { t: 'build', en: 'I am going to book a table', ru: 'Я собираюсь забронировать столик', a: 'Je vais réserver une table.' },
    ],
  },
  {
    id: 'g11', e: '🕒', en: 'Time, days and dates', ru: 'Время, дни и даты',
    sum: [
      X('Time: Il est + number + heure(s). Il est trois heures. Il est midi. Quarter: et quart (+15), et demie (+30), moins le quart (−15). Il est huit heures et quart.',
        'Время: Il est + число + heure(s). Il est trois heures. Il est midi. Четверть: et quart (+15), et demie (+30), moins le quart (−15). Il est huit heures et quart.'),
      X('At a time: à + hour. À sept heures. From … to …: de sept heures à dix heures. Days have no article for one day: lundi (this Monday), le lundi (every Monday). Dates: le 5 octobre, le premier mai.',
        'В какое время: à + час. À sept heures. С … до …: de sept heures à dix heures. У дней недели нет артикля, если речь об одном дне: lundi (в этот понедельник), le lundi (по понедельникам). Даты: le 5 octobre, le premier mai.'),
    ],
    table: { head: ['', 'French', ''], rows: [['8:00', 'huit heures', ''], ['8:15', 'huit heures et quart', ''], ['8:30', 'huit heures et demie', ''], ['8:45', 'neuf heures moins le quart', ''], ['12:00', 'midi', '']] },
    ex: [['À quelle heure est le petit-déjeuner ?', 'What time is breakfast?', 'Во сколько завтрак?'], ['De sept heures à dix heures.', 'From seven to ten.', 'С семи до десяти.'], ['Il est midi.', 'It is noon.', 'Полдень.'], ['Le musée est fermé le lundi.', 'The museum is closed on Mondays.', 'Музей закрыт по понедельникам.']],
    mist: X('Months and days are not capitalised in French. For dates use cardinal numbers except the first: le 2 juin, le premier juin. In everyday speech the 24-hour clock is common for schedules: quatorze heures.',
      'Месяцы и дни недели пишутся с маленькой буквы. В датах числа количественные, кроме первого: le 2 juin, le premier juin. В расписаниях часто используют 24 часа: quatorze heures.'),
    quiz: [
      { t: 'mc', q: 'Il est ___.', o: ['trois heures', 'trois heure', 'à trois heures'], a: 0, w: X('Il est trois heures.', 'Il est trois heures.') },
      { t: 'mc', q: '8:15 = huit heures et ___', o: ['quart', 'demie', 'minutes'], a: 0, w: X('et quart = quarter past.', 'et quart = пятнадцать минут.') },
      { t: 'mc', q: '8:30 = huit heures et ___', o: ['quart', 'demie', 'cinq'], a: 1, w: X('et demie = half past.', 'et demie = половина.') },
      { t: 'mc', q: '8:45 = neuf heures ___ le quart', o: ['moins', 'plus', 'et'], a: 0, w: X('moins le quart = quarter to.', 'moins le quart = без четверти.') },
      { t: 'fill', q: 'Le petit-déjeuner est à sept ___.', a: ['heures'], w: X('sept heures.', 'sept heures.') },
      { t: 'mc', q: 'Le musée est fermé ___ lundi. (every Monday)', o: ['le', 'en', 'au'], a: 0, w: X('le lundi = every Monday.', 'le lundi = каждый понедельник.') },
      { t: 'build', en: 'What time is breakfast?', ru: 'Во сколько завтрак?', a: 'À quelle heure est le petit-déjeuner ?' },
    ],
  },
  {
    id: 'g12', e: '🥖', en: 'Some and quantities: du, de la, des, de', ru: 'Количество: du, de la, des, de',
    sum: [
      X('To mean “some” of something you cannot count, use du (m), de la (f), de l’ (vowel): du pain, de la salade, de l’eau. For plural things use des: des légumes.',
        'Чтобы сказать «немного» чего-то неисчисляемого, используют du (м.), de la (ж.), de l’ (перед гласной): du pain, de la salade, de l’eau. Для множественного — des: des légumes.'),
      X('After a quantity word the article disappears and de is used: beaucoup de pain, un kilo de pommes, une bouteille d’eau. After a negation too: Je ne veux pas de sucre.',
        'После слова количества артикль пропадает и ставится de: beaucoup de pain, un kilo de pommes, une bouteille d’eau. После отрицания тоже: Je ne veux pas de sucre.'),
    ],
    table: { head: ['', 'French', ''], rows: [['m', 'du pain', 'some bread'], ['f', 'de la salade', 'some salad'], ['vowel', 'de l’eau', 'some water'], ['pl', 'des légumes', 'some vegetables'], ['quantity', 'un kilo de pommes', 'a kilo of apples']] },
    ex: [['Je voudrais de l’eau.', 'I would like some water.', 'Я хотела бы воды.'], ['Je voudrais du pain.', 'I would like some bread.', 'Я хотела бы хлеба.'], ['Un kilo de pommes, s’il vous plaît.', 'A kilo of apples, please.', 'Килограмм яблок, пожалуйста.'], ['Une carafe d’eau', 'a carafe of water', 'графин воды']],
    mist: X('Russian uses the genitive here, French uses du / de la / des. Do not say “un kilo des pommes”: after a quantity it is de.',
      'Русский использует родительный падеж, французский — du / de la / des. Нельзя сказать «un kilo des pommes»: после количества ставится de.'),
    quiz: [
      { t: 'mc', q: 'Je voudrais ___ eau.', o: ['de l’', 'du', 'de la'], a: 0, w: X('eau starts with a vowel: de l’eau.', 'eau начинается с гласной: de l’eau.') },
      { t: 'mc', q: 'Je voudrais ___ pain.', o: ['du', 'de la', 'des'], a: 0, w: X('pain is masculine: du pain.', 'pain мужского рода: du pain.') },
      { t: 'mc', q: 'Un kilo ___ pommes.', o: ['de', 'des', 'du'], a: 0, w: X('After a quantity: de.', 'После количества: de.') },
      { t: 'mc', q: 'Je voudrais ___ salade.', o: ['de la', 'du', 'des'], a: 0, w: X('salade is feminine: de la salade.', 'salade женского рода: de la salade.') },
      { t: 'mc', q: 'Je ne veux pas ___ sucre.', o: ['de', 'du', 'le'], a: 0, w: X('After a negation: de.', 'После отрицания: de.') },
      { t: 'fill', q: 'Vous avez ___ huîtres ?', a: ['des'], w: X('Plural, some: des.', 'Множественное: des.') },
      { t: 'build', en: 'A carafe of water, please', ru: 'Графин воды, пожалуйста', a: 'Une carafe d’eau, s’il vous plaît.' },
    ],
  },
];
