#!/usr/bin/env python3
"""Records every text from tools/audio_texts.json with the macOS voice Thomas into audio/<key>.m4a
and writes js/audio-manifest.js. Needs macOS (`say`, `afconvert`). Existing files are kept.
Run: node tools/audio_texts.js && python3 tools/make_audio.py"""
import json, os, subprocess, tempfile, pathlib, sys
from concurrent.futures import ThreadPoolExecutor

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'audio'
OUT.mkdir(exist_ok=True)
VOICE, RATE = 'Thomas', '165'
items = json.loads((ROOT / 'tools/audio_texts.json').read_text(encoding='utf8'))

def make(it):
    dst = OUT / (it['key'] + '.m4a')
    if dst.exists() and dst.stat().st_size > 500:
        return True
    with tempfile.TemporaryDirectory() as td:
        aiff = os.path.join(td, 'c.aiff')
        try:  # `say` sometimes hangs when many run at once, so each call has a time limit and one retry
            for attempt in (1, 2):
                try:
                    r = subprocess.run(['say', '-v', VOICE, '-r', RATE, '-o', aiff, '--', it['text']], capture_output=True, timeout=40)
                    break
                except subprocess.TimeoutExpired:
                    r = None
        except Exception as e:
            print('say error', it['text'], e); return False
        if r is None or r.returncode != 0 or not os.path.exists(aiff):
            print('say failed', it['text']); return False
        r = subprocess.run(['afconvert', aiff, str(dst), '-f', 'm4af', '-d', 'aac', '-b', '40000', '-c', '1'], capture_output=True)
        if r.returncode != 0:
            print('afconvert failed', it['text'], r.stderr[:200]); return False
    return True

with ThreadPoolExecutor(max_workers=4) as ex:
    ok = list(ex.map(make, items))
print('made', sum(ok), 'of', len(items))
keys = [it['key'] for it, good in zip(items, ok) if good]
for f in OUT.glob('*.m4a'):   # drop clips whose text is no longer in the list
    if f.stem not in set(keys):
        f.unlink()
(ROOT / 'js/audio-manifest.js').write_text(
    "/* Generated by tools/make_audio.py: the clips that exist in audio/. */\nconst CLIPS = new Set(" + json.dumps(keys) + ");\n", encoding='utf8')
total = sum((OUT / (k + '.m4a')).stat().st_size for k in keys)
print('total MB', round(total / 1e6, 1), 'avg KB', round(total / len(keys) / 1e3, 1))
sys.exit(0 if all(ok) else 1)
